version: "3.4"

services:
  database:
    image: mongo:latest
    container_name: cse301.database
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27018:27017

  api:
    image: cse301/api
    build: ./jitsi-api
    container_name: cse301.api
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - DB_URL=mongodb://database/jitsi
    ports:
      - 4567:4000

  web:
    image: cse301/web
    build: ./jitsi-meet
    container_name: cse301.web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - 3456:3000
