version: "3.4"

services:
  database:
    image: mongo:latest
    container_name: jitsi-database
    restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27018:27017

  api:
    image: jitsi-api
    build: ./jitsi-api
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - PORT=4000
      - DB_URL=mongodb://database/jitsi
      - ACCESS_TOKEN_SECRET=jitsi-api
    ports:
      - 4000:4000

  meet:
    image: jitsi-meet
    build: ./jitsi-meet
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - 3000:3000
