
export const ADD_ALERT= "ADD_ALERT"
export const REMOVE_ALERT= "REMOVE_ALERT"
export const GET_LOGIN= "GET_LOGIN"
export const LOGIN_SUCCESS= "LOGIN_SUCCESS"
export const LOGOUT_SUCCESS= "LOGOUT_SUCCESS"
export const GET_LOGOUT= "GET_LOGOUT"